### PR TITLE
Simplify testing initialize function

### PR DESCRIPTION
**Pull request by Benjamintf1**
Signed-off-by: David Timm <dtimm@pivotal.io>
Co-authored-by: David Timm <dtimm@pivotal.io>

### CODE REVIEW

**Comment by dtimm** [comment]
I consent!

**Comment by adrcunha** [comment]
Thanks for fixing my bad code. :D

/lgtm
/approve

**Comment by Benjamintf1** [comment]
@adrcunha That's all on us actually.

**Comment by adrcunha** [comment]
@googlebot I consent. I signed it. Whatever

**Comment by adrcunha** [comment]
@googlebot I consent. I signed it. Whatever

**Comment by adrcunha** [comment]
I overrode the CLA due to https://github.com/knative/serving/issues/1439

**Pull request merged**
