### PR TITLE
updates dependencies to match other knative projects

### LINKED ISSUE #34: k8s.io deps are out of sync with the rest of knative
I believe most knative repos are using "kubernetes-1.12.6" for their k8s.io dependencies. It looks like observability is not (e.g., https://github.com/knative/observability/blob/94718bbb2999e84330d7de3b3e761d03c514e59f/go.mod#L38)

The following should not result in a diff:

```bash
for repo in $(cat go.mod | egrep '^\s+k8s.io' | awk '{print $1}'); do 
  go get $repo@kubernetes-1.12.6
done
```

After doing so, it looks like there are compile errors:

```
$ go test ./...
# github.com/knative/observability/pkg/client/clientset/versioned/typed/sink/v1alpha1/fake
pkg/client/clientset/versioned/typed/sink/v1alpha1/fake/fake_clusterlogsink.go:134:44: too many arguments in call to testing.NewPatchSubresourceAction
	have (schema.GroupVersionResource, string, string, types.PatchType, []byte, []string...)
	want (schema.GroupVersionResource, string, string, []byte, ...string)
pkg/client/clientset/versioned/typed/sink/v1alpha1/fake/fake_clustermetricsink.go:134:44: too many arguments in call to testing.NewPatchSubresourceAction
	have (schema.GroupVersionResource, string, string, types.PatchType, []byte, []string...)
	want (schema.GroupVersionResource, string, string, []byte, ...string)
pkg/client/clientset/versioned/typed/sink/v1alpha1/fake/fake_logsink.go:134:44: too many arguments in call to testing.NewPatchSubresourceAction
	have (schema.GroupVersionResource, string, string, types.PatchType, []byte, []string...)
	want (schema.GroupVersionResource, string, string, []byte, ...string)
pkg/client/clientset/versioned/typed/sink/v1alpha1/fake/fake_metricsink.go:134:44: too many arguments in call to testing.NewPatchSubresourceAction
	have (schema.GroupVersionResource, string, string, types.PatchType, []byte, []string...)
	want (schema.GroupVersionResource, string, string, []byte, ...string)
```

### PR DESCRIPTION
**Pull request by poy**
Ran the following to update:
```bash
for repo in $(cat go.mod | egrep '^\s+k8s.io' | awk '{print $1}'); do
  go get $repo@kubernetes-1.12.6
done
go get k8s.io/code-generator@edcfb81a444e5a0f0c799893e4c246ed7b9a3a3a
```

fixes #34

### CODE REVIEW

**Comment by poy** [comment]
Unfortunately, this seems to be suffering from some discrepancies between the code-generator and the k8s.io/client-go/testing library. I'll poke around a bit and see if there is a good solution.

**Comment by wfernandes** [comment]
@poy can we close this PR for now? We can re-open it once it is in a better state.

**Comment by wfernandes** [comment]
I'm going to say we close this. I don't believe this code is being maintained.
/close

**Pull request closed without merging**
