### PR TITLE
Fix CI/presubmit for observability

### PR DESCRIPTION
**Pull request by adrcunha**
Fixes https://github.com/knative/test-infra/issues/749

* fixed/updated e2e-tests.sh script
* fixed/updated presubmit-tests.sh script
* fixed/updated verify-codegen.sh
* added hack/update-deps.sh for easier dep update (aligned with the other repos)
* updated dependencies
* vendored test-infra instead of submoduling it (looks like Prow doesn't like it)
* updated test-infra

### CODE REVIEW

**Comment by adrcunha** [comment]
/hold

Looks like submodules confuse Prow.

**Comment by adrcunha** [comment]
/hold cancel

All issues resolved now, all tests are passing.

**Comment by Benjamintf1** [comment]
@adrcunha Ty for the contribution!

**Pull request merged**
