### PR TITLE
update knative/observability to latest

### PR DESCRIPTION
**Pull request by dtimm**
- Add cluster metric sink
- Add sink status
- Add webhook sink
- Add cluster name if exists in labels
- Use non root for many images
- Add deployment instructions

### CODE REVIEW

**Comment by dtimm** [comment]
This resolves https://github.com/knative/observability/issues/16

**Comment by mdemirhan** [comment]
This is too large to review. My recommendation is to check this in and iterate on this repo going forward.

**Comment by wfernandes** [comment]
/lgtm

- I've ran all the tests locally and verified that all components deploy correctly.
- The test README could use some updates but the main README looks good for now.

**Comment by wfernandes** [comment]
@mdemirhan Sorry didn't see your comment. I'll merge it manually then.

**Comment by wfernandes** [comment]
It seems I don't have write access to push directly or merge to knative/observability. :( 
@dprotaso Do you have write access?

**Pull request merged**
