### PR TITLE
Require TLS when validating log sink configs

### PR DESCRIPTION
**Pull request by Benjamintf1**
- vendor in code generation
- update all the kubernetes
- update tests for requiring tls

Signed-off-by: Ben Fuller <bfuller@pivotal.io>
Co-authored-by: Ben Fuller <bfuller@pivotal.io>

### CODE REVIEW

**Comment by adrcunha** [comment]
The CLA issue is yet another event of the CLA bot not being able to understand pair programming.

knative/test-infra#770

**Comment by Benjamintf1** [comment]
This pr is sad, we somewhat know the reasons, we're working on it.

**Comment by evankanderson** [comment]
Is this still WIP?

I can toggle the CLA back after I figure out what is making the robot angry, but I don't want to do that until it's ready for a look.

**Comment by evankanderson** [comment]
BTW, I think the CLA-bot is sad because @Benjamintf1 lists a \@pivotal.io email address, and @pianohacker lists an \@gmail.com address.

**Comment by Benjamintf1** [comment]
@evankanderson Yeah, I thought we could preserve the cla status, but it seems like it broke when we force pushed. It's not really a wip in some ways. Basically, because the validator has to be built with telegraf as a runtime dependency, we build it with a docker image, which doesn't seem to work as well with ko(maybe we just don't know the secrets of ko), so it's pinned to a version we've built in the past(and we haven't built a non-sha labeled version of it since working on this feature).

**Pull request closed without merging**
